name: CheckFormat
on:
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: |
          npm install
      - name: CheckPrettier
        run: |
          npm run test:prettier
      - name: CheckJS
        run: |
          npm run test:js
      - name: CheckCSS
        run: |
          npm run test:css